import type { Project } from "../content/types.ts";

/*
 * Route metadata shared by the app (usePageMeta) and the build, which writes
 * it into each route's static HTML for crawlers and link previews that don't
 * run JavaScript. No React imports: vite.config.ts loads this module.
 */

/**
 * Public origin used in canonical, Open Graph, sitemap and JSON-LD URLs.
 * Set SITE_URL in the build environment (e.g. Vercel env vars) to change it;
 * this is the fallback. Switch to https://aishwaryarajtyagi.com once that
 * domain resolves.
 */
export const DEFAULT_SITE_URL = "https://aishwarya-dev-ten.vercel.app";
export const siteUrlFrom = (value?: string) => (value || DEFAULT_SITE_URL).replace(/\/+$/, "");

// Replaced at build time by vite.config.ts (define); undefined in Node scripts.
declare const __SITE_URL__: string | undefined;
export const SITE_URL = typeof __SITE_URL__ === "string" ? __SITE_URL__ : DEFAULT_SITE_URL;

export const DEFAULT_TITLE = "Aishwarya Raj Tyagi — Full Stack Developer";
export const DEFAULT_DESCRIPTION =
  "Aishwarya Raj Tyagi — Full Stack Developer with 5+ years of experience building scalable, production-ready web applications in React, Next.js, and Node.js.";
/** Site-wide 1200×630 share card (scripts/og-images.mjs). */
export const DEFAULT_IMAGE = "/og/site.jpg";
export const NOT_FOUND_TITLE = "Page not found — Aishwarya Raj Tyagi";

export const projectPath = (p: Pick<Project, "id">) => `/work/${p.id}`;

export const projectMeta = (p: Project) => ({
  title: `${p.title} — Aishwarya Raj Tyagi`,
  description: p.summary,
  path: projectPath(p),
  /** 1200×630 share card generated by scripts/og-images.mjs. */
  image: `/og/${p.id}.jpg`,
});
