// Generated by scripts/optimize-images.mjs. Do not edit by hand.

export interface ImageMeta { width: number; height: number; widths: number[]; placeholder: string }

export const projectImages: Record<string, ImageMeta> = {
  "alinkriti": {
    "width": 1897,
    "height": 861,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoYAAsAPu1iqU2ppaOiMAgBMB2JQBOgBCg9lNDl0MbGOHgAAPKVR4Ipv9MhzXKVRQ1CKcsRC+fJjXhYtKWT0Mz8LHPtISd18e+T2RjT3Q1kmP9nBgAAAA=="
  },
  "sofisam": {
    "width": 1885,
    "height": 852,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoYAAsAPu1orU2ppqSiMAgBMB2JZwAAW+sciQ4uRH0AAP7cy7jzAdYC8CYBizb4aXqRUV55K0kNtiIwL7Qxyb/QAAA="
  },
  "gulf-connect-consultancy": {
    "width": 1885,
    "height": 857,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQAwCdASoYAAsAPu1iqk2ppaQiMAgBMB2JZwCzgC0H4cIIQAD+78LYFu6Dv12XN+FnIR1KPa24qYUbu42bNhts8gGaAAAA"
  },
  "country-kids": {
    "width": 1886,
    "height": 842,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAABwAwCdASoYAAsAPu1kqk4ppaQiMAgBMB2JZwC+SC0H3QTBS4AA/vBc59bk99jfzbOUbSMd2np5yYDnPmgAAA=="
  },
  "trux360": {
    "width": 1279,
    "height": 778,
    "widths": [
      640,
      1024,
      1279
    ],
    "placeholder": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoYAA8APu1mqk4ppaOiMAgBMB2JZwAAW8PBPovLpa4GwAD+8AZA0U+7K670r7ABETxe3gNdMncS1scFXL6Wu0/gOAA="
  },
  "tasknest": {
    "width": 1280,
    "height": 800,
    "widths": [
      640,
      1024,
      1280
    ],
    "placeholder": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoYAA8APu1iqk2ppaQiMAgBMB2JZACo9CHSOhQY2MBC3n4wAP65Hk9r9T/ishFQRPPqVw4jnffhMHvXilAeFZIua6oc0NE8Bq4BWgW3P++f4AAA"
  },
  "bridge18": {
    "width": 1655,
    "height": 756,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAwCdASoYAAsAPu1orU2ppqSiMAgBMB2JYwABJP+0D0J8MRy0ugAA/v3CjFZlzDfBWeu+r6awAcwxx9ON/45NXjnAAA=="
  },
  "auto-connex": {
    "width": 1412,
    "height": 902,
    "widths": [
      640,
      1024,
      1412
    ],
    "placeholder": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAwAwCdASoYAA8APu1iqU2ppaQiMAgBMB2JaQAAW+/7ZhQAAP7ypOhdfhT3UIuhk4LFyAAA"
  },
  "zerocaters": {
    "width": 1868,
    "height": 860,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoYAAsAPu1mq04ppaQiMAgBMB2JQBgbhEPb4mMhfO76KfAAAP7x231sjFPzd/qWvh8ah6dgq8rsrvP0iO+LB1iqj637b2+6B+ZcWZmpApe8s8bkAAA="
  },
  "demisty5": {
    "width": 1832,
    "height": 823,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoYAAsAPu1yrU+pp6QiMAgBMB2JZwDA3CHfUd7w25zzH8AA/u+2cg4JeNR8NC3VNF8TMB3tT1+ElJzTpK9g63mTsodQgAAA"
  },
  "yourdmarc": {
    "width": 1463,
    "height": 789,
    "widths": [
      640,
      1024,
      1463
    ],
    "placeholder": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JZQCdAC0HagAA/u4CDAIqtsq5cF2OrRZkgAX7rOGj1l3GsMBnEtXTnfMAAA=="
  },
  "generic-ideas": {
    "width": 547,
    "height": 488,
    "widths": [
      547
    ],
    "placeholder": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACQBACdASoYABUAPu1qqk8ppiOjMBgIATAdiWIApyX/4B5yPe2QnuWXnf7DNSAA+NxMVlBoyLBPu4JaF07nIYv0zlPf+zctTXsjCaM0vPCuI9Kq3yP/xC3nKx3m3XvSADRJy6C09OmQyoLiEuHxWFAA"
  },
  "golden-harvest-mango": {
    "width": 1899,
    "height": 865,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoYAAsAPu1mqk4ppaOiMAgBMB2JZgCw7Gk6yj5OrSB09xYAAP79vVQ7CFhaotv86PK4ZWYslkOsw61UyJMpRBTlD7gaxQY0ZarKFsHNVoLVcCFpG4RFAAAA"
  },
  "snapshot-pro": {
    "width": 1280,
    "height": 800,
    "widths": [
      640,
      1024,
      1280
    ],
    "placeholder": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoYAA8APu1krU6ppaSiMAgBMB2JagC06Bt9YmofnzkTwAD9mAVFOA9/WYjtnYWI+YF08BUbVS3umeP+xeAL0eR6ggwrjWKgdngMZAAA"
  },
  "chrome-extension": {
    "width": 1855,
    "height": 836,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoYAAsAPu1iqU2ppaOiMAgBMB2JYgCdABRlpXqXPCQA6M6/Xxxx45n+Jbf87ccjXa31cAAxvEMjxdkcwif19SbS8+79oTpRxkICjAFsAAA="
  },
  "paint-memories": {
    "width": 974,
    "height": 650,
    "widths": [
      640,
      974
    ],
    "placeholder": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoYABAAPu1kq04ppaQiMAgBMB2JQBhmhDwKcCKDK1jkPAAA/vACb98rmYpLPEuf0u8uwXgL1lhUfh41IF9wG2tI5ySrAN+ZPHnqGgoAAAA="
  },
  "bestow-india": {
    "width": 1899,
    "height": 787,
    "widths": [
      640,
      1024,
      1600
    ],
    "placeholder": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoYAAoAPu1iqU2ppaOiMAgBMB2JQBYdhDv/xkvflncrFWAA8qdzvSx2WzTklRRR3vdsK3tkD+bgnFgyG5or1X8LBduLU5n3uZrZrmiL+YgAAA=="
  },
  "trackyoursecurity": {
    "width": 1416,
    "height": 802,
    "widths": [
      640,
      1024,
      1416
    ],
    "placeholder": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCdAC0Jwf8NzAD+75XwD9WgLbtrLADoOL5G9BZHGX0VqHHV+xTa3G6plUuv05IvJ4QAAAA="
  }
};
