// Generated by scripts/build-content.mjs from legacy/content-extracted.json. Do not edit by hand.

export const profile = {
  "name": "Aishwarya Raj Tyagi",
  "title": "Full Stack Developer",
  "yearsExperience": "5+",
  "shortBio": "Full Stack Developer with 5+ years of experience crafting fast, scalable, production-ready web applications. React specialist building modern SaaS products end-to-end.",
  "description": "I build modern web products end-to-end — from pixel-perfect React interfaces to robust Node.js APIs. Over the last 5+ years I've shipped 15+ client products across SaaS, fintech, logistics, and e-commerce, with a focus on clean architecture, performance, and great UX.",
  "email": "aishraj05@gmail.com",
  "github": "https://github.com/aishrt",
  "linkedin": "https://www.linkedin.com/in/aishwarya-raj-tyagi/"
} as const;

export const stats = [
  {
    "label": "Years Experience",
    "value": "5+"
  },
  {
    "label": "Projects Delivered",
    "value": "15+"
  },
  {
    "label": "Happy Clients",
    "value": "12+"
  }
] as const;

export const copy = {
  "heroBadge": "Available for Hire & Freelance",
  "heroGreeting": "Hi, I'm",
  "heroCodeCard": {
    "file": "developer.ts",
    "status": "Open to work",
    "stack": [
      "React",
      "Node",
      "TS",
      "Shopify"
    ],
    "chips": [
      "Next.js",
      "Tailwind",
      "MongoDB"
    ]
  },
  "aboutEyebrow": "About Me",
  "aboutHeading": "Building products that people love using.",
  "projectsEyebrow": "Selected Work",
  "projectsHeading": "Projects that ship to production",
  "projectsIntro": "A selection of products I've built end-to-end — SaaS platforms, fintech tools, and full-stack web apps used in production by real businesses.",
  "skillsEyebrow": "Tech Stack",
  "skillsHeading": "Skills & Tools",
  "skillsIntro": "The technologies I use to design, build, and ship modern web products end-to-end.",
  "contactEyebrow": "Contact",
  "contactHeading": "Let's start a Project Together",
  "contactIntro": "I'm interested in building scalable products and collaborating with ambitious teams. If you're looking for a developer who values design and performance, reach out.",
  "contactEmailNote": "Expect a response within 24 hours",
  "contactLinkedIn": {
    "title": "Live Chat",
    "subtitle": "Available on LinkedIn",
    "note": "Quickest for casual queries"
  },
  "contactGithub": {
    "title": "Wanna see my technical journey?",
    "body": "Check out my projects and repositories on GitHub. I build in the open.",
    "cta": "View Github Repository"
  },
  "formSuccess": "Message sent successfully! I'll get back to you within 24 hours.",
  "formError": "Failed to send message. Please try again or contact me directly.",
  "footerCredit": "Crafted with React, Tailwind & Framer Motion."
} as const;

export const phone = {
  "tel": "7451020300",
  "label": "Scan to Call"
} as const;

export const emailjsConfig = {
  "publicKey": "0ktzjMk1nlEZBPGmM",
  "serviceId": "service_m6kus53",
  "templateId": "template_rjqoknq"
} as const;
