// Generated by scripts/build-content.mjs from legacy/content-extracted.json. Do not edit by hand.

import type { Project, ProjectCategory } from "./types.ts";

export const projectCategories: ProjectCategory[] = [
  {
    "key": "all",
    "label": "All Projects"
  },
  {
    "key": "shopify",
    "label": "Shopify"
  },
  {
    "key": "fullstack",
    "label": "Full Stack"
  },
  {
    "key": "web",
    "label": "Web"
  },
  {
    "key": "other",
    "label": "Tools & Add-ons"
  }
];

export const projects: Project[] = [
  {
    "id": "alinkriti",
    "title": "Alinkriti",
    "summary": "Custom Shopify e-commerce store for a lifestyle brand with a tailored storefront, curated catalog, and secure checkout.",
    "description": "A custom Shopify storefront built for Alinkriti, featuring bespoke theme customization, a curated product catalog, optimized collection and product pages, and a smooth, secure checkout experience. The store is designed for high conversion with responsive layouts, fast load times, and an elegant, brand-aligned shopping journey across mobile and desktop.",
    "technologies": [
      "Shopify",
      "Liquid",
      "E-commerce",
      "Theme Customization",
      "Responsive Design"
    ],
    "liveUrl": "https://alinkriti.com",
    "featured": true,
    "category": "shopify"
  },
  {
    "id": "sofisam",
    "title": "SOFISAM",
    "summary": "Global corporate advisory platform for a Dubai-based firm offering strategic consulting, advisory, and structuring services.",
    "description": "The corporate website for SOFISAM FZCO, an international strategic consulting and advisory firm headquartered in the Dubai Multi Commodities Centre (DMCC). The platform presents the firm's confidential, unconflicted advisory offering across strategic consulting, advisory, and structuring, with a detailed five-phase 'Way of Working' engagement methodology, an insights blog covering global markets and family office structuring, contact forms, and newsletter subscription. Built with a clean, fully responsive layout and optimized WebP imagery.",
    "technologies": [
      "React",
      "Vercel",
      "Responsive Design",
      "Web Development"
    ],
    "liveUrl": "https://sofisam-seven.vercel.app/",
    "featured": false,
    "category": "web"
  },
  {
    "id": "gulf-connect-consultancy",
    "title": "Gulf Connect Consultancy",
    "summary": "Bilingual (English/Arabic) website for a Dubai consultancy providing investor communications, events, and media services for Gulf capital markets.",
    "description": "A bilingual English/Arabic website for Gulf Connect, a Dubai-based consultancy specialising in investor communications and market positioning across the UAE, Saudi Arabia, Qatar, Kuwait, Bahrain, and Oman. The site showcases services including Investor Roadshows, The Gulf Programme, Media & Arabic Communications, and Advisory, with dedicated sections for investors and insights, a structured enquiry form for engagement requests, and a newsletter signup.",
    "technologies": [
      "Next.js",
      "React",
      "Bilingual (EN/AR)",
      "Responsive Design"
    ],
    "liveUrl": "https://www.gulfconnectconsultancy.com/",
    "featured": false,
    "category": "web"
  },
  {
    "id": "country-kids",
    "title": "Country Kids Learning Center",
    "summary": "Website for a not-for-profit early learning centre in Victoria, Australia, covering rooms, curriculum, fees, and enrolments.",
    "description": "The website for Country Kids Learning Center, a not-for-profit early childhood education centre in Ravenhall, Victoria — 'Rooted in Country. Where every child belongs.' The site guides families through seven age-based rooms from infants to pre-kindergarten, a thematic, play-based curriculum incorporating First Nations perspectives, government-funded kindergarten programs, philosophy, child-safety compliance, fees and Child Care Subsidy information, and an enrolment call-to-action.",
    "technologies": [
      "React",
      "Responsive Design",
      "Web Development"
    ],
    "liveUrl": "https://www.countrykids.au/",
    "featured": false,
    "category": "web"
  },
  {
    "id": "trux360",
    "title": "Trux360",
    "summary": "Enterprise-grade Transport Management System for bulk fuel, petroleum transit, and port-to-depot cargo shipping with real-time tracking.",
    "description": "Trux360 is an enterprise-grade Transport Management System (TMS) and Logistics Coordination platform tailored specifically for bulk fuel, petroleum transit, and port-to-depot cargo shipping. The system bridges the gap between fuel distributors (Organisations), fleet managers (Transporters), ground tracking personnel (Trackies), operational runners (Runners), and border custom clearing professionals (Clearing Agents) to ensure seamless, audit-proof, and real-time tracking of fuel shipments.",
    "technologies": [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Real-time Tracking",
      "Logistics",
      "TMS"
    ],
    "liveUrl": "https://master.d3k9fkzq1x1pde.amplifyapp.com/",
    "featured": true,
    "category": "fullstack"
  },
  {
    "id": "tasknest",
    "title": "TaskNest",
    "summary": "To-do list & task manager with list, board, and calendar views from a side panel. Capture tasks with natural language.",
    "description": "TaskNest is a powerful and intuitive Chrome extension designed to streamline your productivity. It features a side panel interface that provides quick access to your tasks without leaving your current tab. With support for list, board, and calendar views, you can organize your work exactly how you want. The extension also leverages natural language processing to let you capture tasks effortlessly—just type and it understands.",
    "technologies": [
      "Chrome Extension API",
      "TypeScript",
      "React",
      "Natural Language Processing",
      "Manifest V3"
    ],
    "liveUrl": "https://chromewebstore.google.com/detail/tasknest-%E2%80%94-to-do-list-tas/coiljcbmhgkhepaajapkabojjledmdoa",
    "featured": true,
    "category": "other"
  },
  {
    "id": "bridge18",
    "title": "Bridge18",
    "summary": "Enterprise-grade fleet management system for real-time logistics tracking , user and vehicle management and optimization.",
    "description": "A comprehensive fleet management solution that enables real-time tracking, route optimization, and performance analytics. The platform features an intuitive dashboard for managing large-scale logistics operations, monitoring vehicle health, and improving fleet efficiency through data-driven insights.",
    "technologies": [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Real-time Tracking",
      "Analytics"
    ],
    "liveUrl": "https://prod.bridge18.com/dashboard",
    "featured": true,
    "category": "fullstack"
  },
  {
    "id": "auto-connex",
    "title": "Auto Connex",
    "summary": "AI-powered automotive platform built on a monorepo with voice agents, real-time conversations, and intelligent workflows.",
    "description": "An AI-driven automotive platform architected as a monorepo combining multiple services and frameworks. The system leverages large language models, voice-based interactions via ElevenLabs, and real-time conversational AI to streamline automotive workflows. Built with a Hono-based edge API layer, Node.js services, a FastAPI Python backend for AI processing, a React.js frontend, and Better Auth for secure authentication.",
    "technologies": [
      "AI",
      "Hono",
      "Node.js",
      "FastAPI",
      "React",
      "Better Auth",
      "ElevenLabs",
      "Monorepo"
    ],
    "liveUrl": "https://auto-connex.ai/",
    "featured": true,
    "category": "fullstack"
  },
  {
    "id": "zerocaters",
    "title": "Zerocaters",
    "summary": "B2B catering platform for corporate offices enabling bulk order booking and management.",
    "description": "A business-to-business catering platform designed for corporate offices to facilitate bulk order booking. The platform streamlines the catering process for large organizations, providing features for menu selection, order management, delivery scheduling, and payment processing.",
    "technologies": [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Stripe",
      "Firebase Auth",
      "Redis"
    ],
    "liveUrl": "https://zerocater.com/",
    "featured": true,
    "category": "fullstack"
  },
  {
    "id": "demisty5",
    "title": "Demisty5",
    "summary": "Digital privacy and security platform with unlimited threat checks and real-time alerts.",
    "description": "A comprehensive digital security platform enabling unlimited threat checks, real-time alerts, and modules for digital privacy, email security, and social media protection. The platform provides users with tools to protect their digital footprint and maintain online privacy.",
    "technologies": [
      "Angular",
      "Node.js",
      "MongoDB",
      "Firebase",
      "SMTP",
      "Vector DB",
      "Redis"
    ],
    "liveUrl": "https://demysti5.com/",
    "featured": true,
    "category": "fullstack"
  },
  {
    "id": "yourdmarc",
    "title": "YourDMARC",
    "summary": "Smart email authentication platform providing SPF, DKIM, and DMARC compliance with advanced reporting.",
    "description": "A smart email authentication platform that provides SPF, DKIM, and DMARC compliance with advanced reporting, real-time monitoring, and domain security insights to prevent spoofing and enhance email deliverability. The platform helps organizations secure their email infrastructure.",
    "technologies": [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "SMTP",
      "Redis",
      "Real-time Monitoring"
    ],
    "liveUrl": "https://www.yourdmarc.com/",
    "featured": false,
    "category": "fullstack"
  },
  {
    "id": "generic-ideas",
    "title": "Generic Ideas",
    "summary": "E-commerce gift store with curated handpicked products, secure checkout, and same-day delivery.",
    "description": "An online gift store offering a curated collection of products across toys, games, handicrafts, and occasion-based categories. The platform features a polished shopping experience with category browsing, secure SSL-encrypted checkout, gift wrapping options, same-day delivery in select cities, and a rich product detail experience designed for high-conversion retail.",
    "technologies": [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Stripe",
      "E-commerce",
      "Responsive Design"
    ],
    "liveUrl": "http://genericideas.com/",
    "featured": false,
    "category": "fullstack"
  },
  {
    "id": "golden-harvest-mango",
    "title": "Golden Harvest Mango",
    "summary": "E-commerce platform for discovering and purchasing premium quality farm-fresh mangoes.",
    "description": "An e-commerce platform dedicated to offering the finest varieties of mangoes grown with love and care. The platform allows users to browse different mango varieties, manage their cart, and place orders smoothly. It features a beautifully designed frontend and an integrated checkout system for a seamless shopping experience.",
    "technologies": [
      "React",
      "E-commerce",
      "Payment Gateway",
      "Web Development"
    ],
    "liveUrl": "https://goldenharvestmango.com/",
    "featured": false,
    "category": "fullstack"
  },
  {
    "id": "snapshot-pro",
    "title": "SnapShot Pro",
    "summary": "Chrome extension to capture stunning full-page, scrolling, and visible-area website screenshots in HD.",
    "description": "A fast, reliable, and beautifully designed Chrome extension for capturing HD website screenshots. Features include full-page and visible-area capture, sticky-header de-duplication, floating widget hiding, configurable format and quality (PNG/JPEG), filename templates, auto-download, copy to clipboard, and full keyboard control for a power-user workflow.",
    "technologies": [
      "Chrome Extension API",
      "JavaScript",
      "TypeScript",
      "HTML5 Canvas",
      "Manifest V3"
    ],
    "liveUrl": "https://chromewebstore.google.com/detail/lajmpjkepgpiaondpghbajapdgkdaiop?utm_source=item-share-cb",
    "featured": false,
    "category": "other"
  },
  {
    "id": "chrome-extension",
    "title": "Student Chrome Extension",
    "summary": "Chrome extension for discovering discounts, loan offers, and managing finances with real-time data.",
    "description": "A Chrome extension designed to help students discover discounts, loan offers, and manage finances. Features include real-time data from Firebase, privacy-safe site tracking via Chrome History API, and cross-device synchronization for seamless user experience.",
    "technologies": [
      "Chrome Extension API",
      "Firebase",
      "JavaScript",
      "Chrome History API",
      "Real-time Data"
    ],
    "liveUrl": "https://student-chrome-extension.web.app/",
    "featured": false,
    "category": "other"
  },
  {
    "id": "paint-memories",
    "title": "Paint & Memories",
    "summary": "AI-powered custom artwork platform that transforms personal photos into professional traditional paintings.",
    "description": "A high-end creative platform where users can turn their cherished photos into custom artworks. The system offers various styles including Traditional Oil Paint and Classic Watercolour, featuring a seamless selection flow, secure checkout, and professional-grade AI image transformation. Built with a focus on premium user experience and high-fidelity output.",
    "technologies": [
      "React",
      "Node.js",
      "MongoDB",
      "AI Processing",
      "Stripe",
      "Cloudinary"
    ],
    "liveUrl": "https://create.paintandmemories.com/",
    "featured": false,
    "category": "fullstack"
  },
  {
    "id": "bestow-india",
    "title": "Bestow India",
    "summary": "One-Stop Solution Partner for end-to-end people and business development.",
    "description": "We are a 'One-Stop Solution Partner' and a trusted coach for end-to-end people and business development. Our approach combines deep industry expertise, structured frameworks, and advanced AI-driven methodologies to help people and organizations scale sustainably, improve performance, and build future-ready capabilities. We strongly believe in people and the power of people, because people are the true differentiator that sets one organization apart from another.",
    "technologies": [
      "Web Development",
      "Business Expansion",
      "AI Methodologies",
      "React"
    ],
    "liveUrl": "https://www.bestowindia.com/",
    "featured": false,
    "category": "web"
  },
  {
    "id": "trackyoursecurity",
    "title": "Track Your Security",
    "summary": "Next-generation AI-driven security platform with real-time status monitoring, threat level checking, and custom interactive dashboard elements.",
    "description": "A premium, next-generation AI physical security platform with live 24/7 human-verified monitoring and proactive prevention mechanisms. The application features a stunning, state-of-the-art interactive dashboard mock displaying real-time access point status, signal strength, threat levels, and encrypted data channels. Built with rich micro-animations, custom SVG indicators, and HSL tailored colors for an immersive user experience.",
    "technologies": [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "SVG Animations",
      "Responsive Design"
    ],
    "liveUrl": "https://www.trackyoursecurity.com/",
    "featured": true,
    "category": "web"
  }
];
