// Generated by scripts/build-content.mjs from legacy/content-extracted.json. Do not edit by hand.

import type { Skill, SkillCategory } from "./types.ts";

export const skillCategories: SkillCategory[] = [
  {
    "key": "frontend",
    "label": "Frontend",
    "tag": "UI / UX"
  },
  {
    "key": "backend",
    "label": "Backend",
    "tag": "APIs & Logic"
  },
  {
    "key": "database",
    "label": "Databases",
    "tag": "Data Layer"
  },
  {
    "key": "tools",
    "label": "Tools & APIs",
    "tag": "Integrations"
  },
  {
    "key": "devops",
    "label": "DevOps",
    "tag": "Ship & Host"
  }
];

export const skills: Skill[] = [
  {
    "name": "React",
    "category": "frontend",
    "url": "https://react.dev/"
  },
  {
    "name": "Next.js",
    "category": "frontend",
    "url": "https://nextjs.org/"
  },
  {
    "name": "TypeScript",
    "category": "frontend",
    "url": "https://www.typescriptlang.org/"
  },
  {
    "name": "React Native",
    "category": "frontend",
    "url": "https://reactnative.dev/"
  },
  {
    "name": "JavaScript",
    "category": "frontend",
    "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript"
  },
  {
    "name": "Angular",
    "category": "frontend",
    "url": "https://angular.io/"
  },
  {
    "name": "HTML5",
    "category": "frontend",
    "url": "https://developer.mozilla.org/en-US/docs/Web/HTML"
  },
  {
    "name": "CSS3",
    "category": "frontend",
    "url": "https://developer.mozilla.org/en-US/docs/Web/CSS"
  },
  {
    "name": "Tailwind CSS",
    "category": "frontend",
    "url": "https://tailwindcss.com/"
  },
  {
    "name": "Zustand",
    "category": "frontend",
    "url": "https://zustand-demo.pmnd.rs/"
  },
  {
    "name": "React Query",
    "category": "frontend",
    "url": "https://tanstack.com/query/latest"
  },
  {
    "name": "Sonner",
    "category": "frontend",
    "url": "https://sonner.emilkowal.ski/"
  },
  {
    "name": "Node.js",
    "category": "backend",
    "url": "https://nodejs.org/"
  },
  {
    "name": "Express.js",
    "category": "backend",
    "url": "https://expressjs.com/"
  },
  {
    "name": "FastAPI",
    "category": "backend",
    "url": "https://fastapi.tiangolo.com/"
  },
  {
    "name": "Hono",
    "category": "backend",
    "url": "https://hono.dev/"
  },
  {
    "name": "AI Integration",
    "category": "backend",
    "url": "https://openai.com/"
  },
  {
    "name": "MongoDB",
    "category": "database",
    "url": "https://www.mongodb.com/"
  },
  {
    "name": "Redis",
    "category": "database",
    "url": "https://redis.io/"
  },
  {
    "name": "Serverless Database",
    "category": "database",
    "url": "https://aws.amazon.com/serverless/"
  },
  {
    "name": "Vector DB",
    "category": "database",
    "url": "https://www.pinecone.io/"
  },
  {
    "name": "Playwright",
    "category": "tools",
    "url": "https://playwright.dev/"
  },
  {
    "name": "Google Drive API",
    "category": "tools",
    "url": "https://developers.google.com/drive"
  },
  {
    "name": "Stripe",
    "category": "tools",
    "url": "https://stripe.com/"
  },
  {
    "name": "Google Maps API",
    "category": "tools",
    "url": "https://developers.google.com/maps"
  },
  {
    "name": "SMTP",
    "category": "tools",
    "url": "https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol"
  },
  {
    "name": "Claude AI",
    "category": "tools",
    "url": "https://claude.ai/"
  },
  {
    "name": "better-auth",
    "category": "tools",
    "url": "https://www.better-auth.com/"
  },
  {
    "name": "ElevenLabs",
    "category": "tools",
    "url": "https://elevenlabs.io/"
  },
  {
    "name": "Monorepo",
    "category": "tools",
    "url": "https://turbo.build/repo"
  },
  {
    "name": "Cursor",
    "category": "tools",
    "url": "https://cursor.sh/"
  },
  {
    "name": "Chrome Extension API",
    "category": "tools",
    "url": "https://developer.chrome.com/docs/extensions/"
  },
  {
    "name": "VS Code",
    "category": "tools",
    "url": "https://code.visualstudio.com/"
  },
  {
    "name": "Postman",
    "category": "tools",
    "url": "https://www.postman.com/"
  },
  {
    "name": "Escrow",
    "category": "tools",
    "url": "https://www.escrow.com/"
  },
  {
    "name": "Shopify API",
    "category": "tools",
    "url": "https://shopify.dev/"
  },
  {
    "name": "Shopify",
    "category": "tools",
    "url": "https://www.shopify.com/"
  },
  {
    "name": "Sentry",
    "category": "tools",
    "url": "https://sentry.io/welcome/"
  },
  {
    "name": "Firebase",
    "category": "devops",
    "url": "https://firebase.google.com/"
  },
  {
    "name": "Git",
    "category": "devops",
    "url": "https://git-scm.com/"
  },
  {
    "name": "Docker",
    "category": "devops",
    "url": "https://www.docker.com/"
  },
  {
    "name": "Hostinger",
    "category": "devops",
    "url": "https://www.hostinger.com/"
  },
  {
    "name": "AWS Amplify",
    "category": "devops",
    "url": "https://aws.amazon.com/amplify/"
  },
  {
    "name": "cPanel",
    "category": "devops",
    "url": "https://www.cpanel.net/"
  },
  {
    "name": "GitHub",
    "category": "devops",
    "url": "https://github.com/"
  },
  {
    "name": "Netlify",
    "category": "devops",
    "url": "https://www.netlify.com/"
  }
];
