// Generates typed content modules from the verbatim extraction of the live site.
// Source of truth: legacy/content-extracted.json. Text is copied as-is; only
// presentation-only fields (emoji icons, brand colours, proficiency %) are dropped.
import { readFileSync, writeFileSync } from "node:fs";

const src = JSON.parse(readFileSync("legacy/content-extracted.json", "utf8"));
const header = "// Generated by scripts/build-content.mjs from legacy/content-extracted.json. Do not edit by hand.\n\n";
const lit = (v) => JSON.stringify(v, null, 2);

const projects = src.projects.map((p) => ({
  id: p.id,
  title: p.title,
  summary: p.description,
  description: p.longDescription,
  technologies: p.technologies,
  liveUrl: p.liveUrl,
  featured: p.featured,
  category: p.category,
}));

const skillCategories = [
  ...src.skillCategories,
  // Present in the data but never rendered by the old UI; label follows the data key.
  { key: "devops", label: "DevOps", tag: "Ship & Host" },
];
const order = skillCategories.map((c) => c.key);
const skills = src.skills
  .map((s) => ({ name: s.name, category: s.category, url: s.url }))
  .sort((a, b) => order.indexOf(a.category) - order.indexOf(b.category));

writeFileSync(
  "src/content/projects.ts",
  header +
    `import type { Project, ProjectCategory } from "./types";\n\n` +
    `export const projectCategories: ProjectCategory[] = ${lit(src.projectCategories)};\n\n` +
    `export const projects: Project[] = ${lit(projects)};\n`,
);

writeFileSync(
  "src/content/skills.ts",
  header +
    `import type { Skill, SkillCategory } from "./types";\n\n` +
    `export const skillCategories: SkillCategory[] = ${lit(skillCategories)};\n\n` +
    `export const skills: Skill[] = ${lit(skills)};\n`,
);

const { callWidget, emailjs } = src.integrations;
writeFileSync(
  "src/content/profile.ts",
  header +
    `export const profile = ${lit(src.profile)} as const;\n\n` +
    `export const stats = ${lit(src.stats)} as const;\n\n` +
    `export const copy = ${lit(src.copy)} as const;\n\n` +
    `export const phone = ${lit({ tel: callWidget.tel, label: callWidget.label })} as const;\n\n` +
    `export const emailjsConfig = ${lit({ publicKey: emailjs.publicKey, serviceId: emailjs.serviceId, templateId: emailjs.templateId })} as const;\n`,
);

console.log(`projects: ${projects.length}, skills: ${skills.length}, categories: ${skillCategories.length}`);
