// Builds responsive AVIF + WebP variants of every project screenshot from the
// original PNGs in legacy/public, plus a manifest with intrinsic sizes (prevents
// layout shift) and a tiny blurred placeholder.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import sharp from "sharp";

const WIDTHS = [640, 1024, 1600];
const OUT_DIR = "public/img/projects";
const src = JSON.parse(readFileSync("legacy/content-extracted.json", "utf8"));

mkdirSync(OUT_DIR, { recursive: true });
const manifest = {};
let before = 0;
let after = 0;

for (const project of src.projects) {
  const input = `legacy/public${project.image}`;
  const image = sharp(input);
  const { width, height, size } = await image.metadata().then(async (m) => ({ ...m, size: readFileSync(input).length }));
  before += size;

  const widths = [...new Set(WIDTHS.filter((w) => w < width).concat(Math.min(width, WIDTHS.at(-1))))];
  for (const w of widths) {
    const resized = sharp(input).resize({ width: w, withoutEnlargement: true });
    const avif = await resized.clone().avif({ quality: 52, effort: 6 }).toFile(`${OUT_DIR}/${project.id}-${w}.avif`);
    const webp = await resized.clone().webp({ quality: 74 }).toFile(`${OUT_DIR}/${project.id}-${w}.webp`);
    after += avif.size + webp.size;
  }

  const placeholder = await sharp(input).resize({ width: 24 }).blur(1).webp({ quality: 40 }).toBuffer();
  manifest[project.id] = {
    width,
    height,
    widths,
    placeholder: `data:image/webp;base64,${placeholder.toString("base64")}`,
  };
  console.log(`${project.id.padEnd(26)} ${width}x${height} -> ${widths.join(", ")}`);
}

writeFileSync(
  "src/content/images.ts",
  "// Generated by scripts/optimize-images.mjs. Do not edit by hand.\n\n" +
    "export interface ImageMeta { width: number; height: number; widths: number[]; placeholder: string }\n\n" +
    `export const projectImages: Record<string, ImageMeta> = ${JSON.stringify(manifest, null, 2)};\n`,
);
console.log(`\nOriginals: ${(before / 1e6).toFixed(1)} MB. All variants (both formats, all widths): ${(after / 1e6).toFixed(1)} MB.`);
